export interface GalleryItem {
  id: string;
  name: string;
  nameEn: string;
  kanji: string;
  period: string;
  description: string;
  category: 'traditional' | 'modern';
  images: string[];
  color: string; // accent color for the card
}

export const GALLERY: GalleryItem[] = [
  {
    id: 'ukiyoe',
    name: 'Ukiyo-e',
    nameEn: 'Pictures of the Floating World',
    kanji: '浮世絵',
    period: 'Edo Period, 1600–1868',
    description: 'Bold flat colors, strong outlines, scenes of pleasure and nature. The most iconic Japanese print tradition — Hokusai\'s waves, Hiroshige\'s rain.',
    category: 'traditional',
    images: ['/gallery/ukiyoe.png', '/gallery/ukiyoe_2.png'],
    color: '#c23b22',
  },
  {
    id: 'sumie',
    name: 'Sumi-e',
    nameEn: 'Ink Wash Painting',
    kanji: '墨絵',
    period: 'Muromachi Period, 1336–1573',
    description: 'The art of restraint. Every brushstroke is final, every empty space intentional. Monochrome ink on white rice paper, where less is everything.',
    category: 'traditional',
    images: ['/gallery/sumie.png', '/gallery/sumie_2.png'],
    color: '#6b6158',
  },
  {
    id: 'rinpa',
    name: 'Rinpa',
    nameEn: 'Decorative Elegance',
    kanji: '琳派',
    period: 'Edo Period, 1600–1868',
    description: 'Gold leaf, bold patterns, wet-on-wet technique. Where nature meets ornament — Ogata Kōrin\'s irises and Tawaraya Sōtatsu\'s waves.',
    category: 'traditional',
    images: ['/gallery/rinpa.png', '/gallery/rinpa_2.png'],
    color: '#b8963e',
  },
  {
    id: 'kano',
    name: 'Kano School',
    nameEn: 'Imperial Screen Painting',
    kanji: '狩野派',
    period: 'Muromachi–Edo, 1400–1868',
    description: 'The official painters of Japan. Gold leaf screens, powerful brushwork — the bridge between Chinese ink and Japanese color.',
    category: 'traditional',
    images: ['/gallery/kano.png', '/gallery/kano_2.png'],
    color: '#8a6e2e',
  },
  {
    id: 'shinhanga',
    name: 'Shin-hanga',
    nameEn: 'New Prints',
    kanji: '新版画',
    period: 'Taishō–Shōwa, 1910–1960',
    description: 'Where ukiyo-e meets Western light and shadow. Kawase Hasui\'s rain, Yoshitoshi\'s moon — romantic, atmospheric, modern.',
    category: 'traditional',
    images: ['/gallery/shinhanga.png', '/gallery/shinhanga_2.png'],
    color: '#4a6080',
  },
  {
    id: 'enso',
    name: 'Zen Ensō',
    nameEn: 'Circle of Enlightenment',
    kanji: '禅円相',
    period: 'Kamakura Period, 1185–1333',
    description: 'A single brushstroke. A moment of absolute presence. The ensō circle — imperfect, open, and complete all at once.',
    category: 'traditional',
    images: ['/gallery/enso.png', '/gallery/enso_2.png'],
    color: '#2d2926',
  },
  {
    id: 'anime',
    name: 'Anime Art',
    nameEn: 'Japanese Animation',
    kanji: 'アニメ',
    period: '1960s–Present',
    description: 'From Ghibli\'s watercolor skies to Cyberpunk\'s neon rain. The visual language that reshaped global imagination.',
    category: 'modern',
    images: ['/gallery/anime.png', '/gallery/anime_2.png'],
    color: '#e8596e',
  },
  {
    id: 'manga',
    name: 'Manga Ink',
    nameEn: 'Japanese Comics',
    kanji: '漫画',
    period: '12th Century–Present',
    description: 'Dynamic linework, dramatic speed lines, screentone shading. From Hokusai\'s early sketches to modern shonen epics.',
    category: 'modern',
    images: ['/gallery/manga.png', '/gallery/manga_2.png'],
    color: '#1a1a1a',
  },
  {
    id: 'chibi',
    name: 'Chibi Kawaii',
    nameEn: 'Cute & Adorable',
    kanji: 'ちびかわいい',
    period: '1970s–Present',
    description: 'Tiny bodies, enormous eyes, maximum cuteness. The kawaii aesthetic that conquered the world — from Hello Kitty to modern character design.',
    category: 'modern',
    images: ['/gallery/chibi.png', '/gallery/chibi_2.png'],
    color: '#f5a0b5',
  },
  {
    id: 'watercolor',
    name: 'Japanese Watercolor',
    nameEn: 'Nihonga Watercolor',
    kanji: '水彩',
    period: 'Meiji Period–Present',
    description: 'Translucent washes of color on washi paper. Where Eastern brush meets Western watercolor — luminous, delicate, meditative.',
    category: 'modern',
    images: ['/gallery/watercolor.png', '/gallery/watercolor_2.png'],
    color: '#5a8fa8',
  },
  {
    id: 'ukiyoe_portrait',
    name: 'Ukiyo-e Bijin',
    nameEn: 'Beauty Portraits',
    kanji: '浮世絵肖像',
    period: 'Edo Period, 1600–1868',
    description: 'The bijin-ga tradition — portraits of beauties by Utamaro and Sharaku. Elongated proportions, intricate textile patterns, enigmatic expressions.',
    category: 'traditional',
    images: ['/gallery/ukiyoe_portrait.png', '/gallery/ukiyoe_portrait_2.png'],
    color: '#c23b22',
  },
  {
    id: 'neon',
    name: 'Neo-Tokyo',
    nameEn: 'Cyberpunk Japan',
    kanji: '新東京',
    period: '1980s–Present',
    description: 'Where tradition collides with technology. Neon kanji bleeding through rain, holographic cherry blossoms, the future through Japanese eyes.',
    category: 'modern',
    images: ['/gallery/japanese_neon.png', '/gallery/neon_2.png'],
    color: '#8b5cf6',
  },
];