export interface GalleryItem {
  id: string;
  name: string;
  nameEn: string;
  kanji: string;
  period: string;
  description: string;
  category: 'traditional' | 'modern' | 'lifestyle';
  images: string[];
  color: string;
}

export const GALLERY: GalleryItem[] = [
  // ──── TRADITIONAL ART ────
  {
    id: 'ukiyoe',
    name: 'Ukiyo-e',
    nameEn: 'Pictures of the Floating World',
    kanji: '浮世絵',
    period: 'Edo Period, 1600–1868',
    description: 'Bold flat colors, strong outlines, scenes of pleasure and nature. The most iconic Japanese print tradition — Hokusai\'s waves, Hiroshige\'s rain.',
    category: 'traditional',
    images: ['/gallery/ukiyoe.png', '/gallery/ukiyoe_2.png'],
    color: '#c23b22',
  },
  {
    id: 'sumie',
    name: 'Sumi-e',
    nameEn: 'Ink Wash Painting',
    kanji: '墨絵',
    period: 'Muromachi Period, 1336–1573',
    description: 'The art of restraint. Every brushstroke is final, every empty space intentional. Monochrome ink on white rice paper, where less is everything.',
    category: 'traditional',
    images: ['/gallery/sumie.png', '/gallery/sumie_2.png'],
    color: '#6b6158',
  },
  {
    id: 'rinpa',
    name: 'Rinpa',
    nameEn: 'Decorative Elegance',
    kanji: '琳派',
    period: 'Edo Period, 1600–1868',
    description: 'Gold leaf, bold patterns, wet-on-wet technique. Where nature meets ornament — Ogata Korin\'s irises and Tawaraya Sotatsu\'s waves.',
    category: 'traditional',
    images: ['/gallery/rinpa.png', '/gallery/rinpa_2.png'],
    color: '#b8963e',
  },
  {
    id: 'kano',
    name: 'Kano School',
    nameEn: 'Imperial Screen Painting',
    kanji: '狩野派',
    period: 'Muromachi–Edo, 1400–1868',
    description: 'The official painters of Japan. Gold leaf screens, powerful brushwork — the bridge between Chinese ink and Japanese color.',
    category: 'traditional',
    images: ['/gallery/kano.png', '/gallery/kano_2.png'],
    color: '#8a6e2e',
  },
  {
    id: 'shinhanga',
    name: 'Shin-hanga',
    nameEn: 'New Prints',
    kanji: '新版画',
    period: 'Taishō–Shōwa, 1910–1960',
    description: 'Where ukiyo-e meets Western light and shadow. Kawase Hasui\'s rain, Yoshitoshi\'s moon — romantic, atmospheric, modern.',
    category: 'traditional',
    images: ['/gallery/shinhanga.png', '/gallery/shinhanga_2.png'],
    color: '#4a6080',
  },
  {
    id: 'enso',
    name: 'Zen Ensō',
    nameEn: 'Circle of Enlightenment',
    kanji: '禅円相',
    period: 'Kamakura Period, 1185–1333',
    description: 'A single brushstroke. A moment of absolute presence. The ensō circle — imperfect, open, and complete all at once.',
    category: 'traditional',
    images: ['/gallery/enso.png', '/gallery/enso_2.png'],
    color: '#2d2926',
  },
  {
    id: 'ukiyoe_portrait',
    name: 'Ukiyo-e Bijin',
    nameEn: 'Beauty Portraits',
    kanji: '浮世絵肖像',
    period: 'Edo Period, 1600–1868',
    description: 'The bijin-ga tradition — portraits of beauties by Utamaro and Sharaku. Elongated proportions, intricate textile patterns, enigmatic expressions.',
    category: 'traditional',
    images: ['/gallery/ukiyoe_portrait.png', '/gallery/ukiyoe_portrait_2.png'],
    color: '#c23b22',
  },
  // ──── MODERN & POP ────
  {
    id: 'anime',
    name: 'Anime Art',
    nameEn: 'Japanese Animation',
    kanji: 'アニメ',
    period: '1960s–Present',
    description: 'From Ghibli\'s watercolor skies to cyberpunk neon rain. The visual language that reshaped global imagination.',
    category: 'modern',
    images: ['/gallery/anime.png', '/gallery/anime_2.png'],
    color: '#e8596e',
  },
  {
    id: 'manga',
    name: 'Manga Ink',
    nameEn: 'Japanese Comics',
    kanji: '漫画',
    period: '12th Century–Present',
    description: 'Dynamic linework, dramatic speed lines, screentone shading. From Hokusai\'s early sketches to modern shonen epics.',
    category: 'modern',
    images: ['/gallery/manga.png', '/gallery/manga_2.png'],
    color: '#1a1a1a',
  },
  {
    id: 'chibi',
    name: 'Chibi Kawaii',
    nameEn: 'Cute & Adorable',
    kanji: 'ちびかわいい',
    period: '1970s–Present',
    description: 'Tiny bodies, enormous eyes, maximum cuteness. The kawaii aesthetic that conquered the world — from Hello Kitty to modern character design.',
    category: 'modern',
    images: ['/gallery/chibi.png', '/gallery/chibi_2.png'],
    color: '#f5a0b5',
  },
  {
    id: 'watercolor',
    name: 'Japanese Watercolor',
    nameEn: 'Nihonga Watercolor',
    kanji: '水彩',
    period: 'Meiji Period–Present',
    description: 'Translucent washes of color on washi paper. Where eastern brush meets western watercolor — luminous, delicate, meditative.',
    category: 'modern',
    images: ['/gallery/watercolor.png', '/gallery/watercolor_2.png'],
    color: '#5a8fa8',
  },
  {
    id: 'neon',
    name: 'Neo-Tokyo',
    nameEn: 'Cyberpunk Japan',
    kanji: '新東京',
    period: '1980s–Present',
    description: 'Where tradition collides with technology. Neon kanji bleeding through rain, holographic cherry blossoms, the future through Japanese eyes.',
    category: 'modern',
    images: ['/gallery/japanese_neon.png', '/gallery/neon_2.png'],
    color: '#8b5cf6',
  },
  // ──── LIFESTYLE & CULTURE ────
  // NEW: Daily Life Collection (30 images of people in Japanese art eras)
  {
    id: 'lifestyle_daily',
    name: 'Daily Life Collection',
    nameEn: 'People & Traditions',
    kanji: '日常生活',
    period: 'All Eras',
    description: '✦ 30 IMAGES — Daily life, traditions, ceremonies, and people across Japanese history. Click to explore: Edo merchants, artisans, tea ceremonies, samurai, festivals, anime & modern Tokyo life.',
    category: 'lifestyle',
    images: [
      '/gallery/lifestyle_ukiyoe_daily_1.png', '/gallery/lifestyle_ukiyoe_daily_2.png',
      '/gallery/lifestyle_ukiyoe_daily_3.png', '/gallery/lifestyle_ukiyoe_daily_4.png',
      '/gallery/lifestyle_sumie_daily_1.png', '/gallery/lifestyle_sumie_daily_2.png',
      '/gallery/lifestyle_rinpa_daily_1.png', '/gallery/lifestyle_rinpa_daily_2.png',
      '/gallery/lifestyle_samurai_daily_1.png', '/gallery/lifestyle_samurai_daily_2.png',
      '/gallery/lifestyle_tea_daily_1.png', '/gallery/lifestyle_tea_daily_2.png',
      '/gallery/lifestyle_garden_daily_1.png', '/gallery/lifestyle_garden_daily_2.png',
      '/gallery/lifestyle_cuisine_daily_1.png', '/gallery/lifestyle_cuisine_daily_2.png',
      '/gallery/lifestyle_kimono_daily_1.png', '/gallery/lifestyle_kimono_daily_2.png',
      '/gallery/lifestyle_anime_daily_1.png', '/gallery/lifestyle_anime_daily_2.png',
      '/gallery/lifestyle_manga_daily_1.png', '/gallery/lifestyle_manga_daily_2.png',
      '/gallery/lifestyle_neon_daily_1.png', '/gallery/lifestyle_neon_daily_2.png',
      '/gallery/lifestyle_watercolor_daily_1.png', '/gallery/lifestyle_watercolor_daily_2.png',
      '/gallery/lifestyle_matsuri_daily_1.png', '/gallery/lifestyle_matsuri_daily_2.png',
      '/gallery/lifestyle_shodo_daily_1.png', '/gallery/lifestyle_zen_daily_1.png',
    ],
    color: '#8a6a4a',
  },
  {
    id: 'lifestyle_wabisabi',
    name: 'Wabi-sabi Living',
    nameEn: 'Beauty in Imperfection',
    kanji: '侘寂の生活',
    period: '15th Century–Present',
    description: '✦ 2 IMAGES — Intimate wabi-sabi moments: ikebana arrangements, afternoon light through shoji screens, weathered beams, peaceful domesticity.',
    category: 'lifestyle',
    images: ['/gallery/lifestyle_wabisabi_daily_1.png', '/gallery/lifestyle_seasons_daily_1.png'],
    color: '#9a8a7a',
  },
  // Original Lifestyle entries
  {
    id: 'garden',
    name: 'Japanese Gardens',
    nameEn: 'Zen Gardens & Landscapes',
    kanji: '枯山水',
    period: 'Heian–Edo, 794–1868',
    description: 'Raked gravel seas, moss-covered islands, arched red bridges over koi ponds. Japanese gardens are landscape paintings you walk through.',
    category: 'lifestyle',
    images: ['/gallery/garden.png', '/gallery/garden_2.png'],
    color: '#5a8a5a',
  },
  {
    id: 'tea_ceremony',
    name: 'Tea Ceremony',
    nameEn: 'The Way of Tea',
    kanji: '茶道',
    period: 'Muromachi Period–Present',
    description: 'A bowl of matcha, a single flower, a scroll on the wall. Chadō — the way of tea — is meditation through motion. Every gesture intentional.',
    category: 'lifestyle',
    images: ['/gallery/tea_ceremony.png', '/gallery/tea_2.png'],
    color: '#7a8a5a',
  },
  {
    id: 'architecture',
    name: 'Japanese Architecture',
    nameEn: 'Temples & Townhouses',
    kanji: '建築',
    period: 'Asuka Period–Present',
    description: 'Five-story pagodas, curved tiled roofs, machiya townhouses with wooden lattices. Architecture that breathes with the seasons.',
    category: 'lifestyle',
    images: ['/gallery/architecture.png', '/gallery/architecture_2.png'],
    color: '#8a6a3a',
  },
  {
    id: 'samurai',
    name: 'Samurai & Bushidō',
    nameEn: 'Way of the Warrior',
    kanji: '武士道',
    period: 'Kamakura–Edo, 1185–1868',
    description: 'Warriors of discipline and honor. Ornate armor, the way of the sword, and the philosophy that shaped a nation — loyalty, mastery, stillness.',
    category: 'lifestyle',
    images: ['/gallery/samurai.png', '/gallery/samurai_2.png'],
    color: '#6b3a3a',
  },
  {
    id: 'kimono',
    name: 'Kimono Fashion',
    nameEn: 'Woven Artistry',
    kanji: '着物',
    period: 'Heian Period–Present',
    description: 'The world\'s most exquisite garment. Gold-thread embroidery, layered seasonal patterns, obi tied in forty different ways. Fashion as art.',
    category: 'lifestyle',
    images: ['/gallery/kimono.png', '/gallery/kimono_2.png'],
    color: '#c44080',
  },
  {
    id: 'cuisine',
    name: 'Japanese Cuisine',
    nameEn: 'Art on a Plate',
    kanji: '食芸',
    period: 'Edo Period–Present',
    description: 'Where food meets art. Kaiseki courses arranged like paintings, ramen that warms the soul, sushi that honors the fish. Taste the seasons.',
    category: 'lifestyle',
    images: ['/gallery/cuisine.png', '/gallery/cuisine_2.png'],
    color: '#d4763a',
  },
  {
    id: 'matsuri',
    name: 'Matsuri Festivals',
    nameEn: 'Sacred Celebrations',
    kanji: '祭',
    period: 'Ancient–Present',
    description: 'Paper lanterns reflected in summer rain, fireworks over shrines, golden mikoshi carried through cheering streets. Japan celebrates like nowhere else.',
    category: 'lifestyle',
    images: ['/gallery/matsuri.png', '/gallery/matsuri_2.png'],
    color: '#e05040',
  },
  {
    id: 'shodo',
    name: 'Shodō Calligraphy',
    nameEn: 'The Way of Writing',
    kanji: '書道',
    period: '7th Century–Present',
    description: 'Black ink meeting white paper — each stroke an irreversible commitment. Calligraphy as meditation, art, and spiritual practice.',
    category: 'lifestyle',
    images: ['/gallery/shodo.png', '/gallery/shodo_2.png'],
    color: '#2d2926',
  },
  {
    id: 'wabisabi',
    name: 'Wabi-sabi Interiors',
    nameEn: 'Beauty in Imperfection',
    kanji: '侘寂',
    period: '15th Century–Present',
    description: 'A cracked tea bowl, a weathered wooden beam, late afternoon light through shoji. The profound beauty of things worn, simple, and honest.',
    category: 'lifestyle',
    images: ['/gallery/wabisabi.png', '/gallery/wabisabi_2.png'],
    color: '#8a7a6a',
  },
  {
    id: 'seasons',
    name: 'Four Seasons',
    nameEn: 'Sakura to Momiji',
    kanji: '四季',
    period: 'Eternal Cycle',
    description: 'Cherry blossoms heralding spring, cicadas singing summer, maple blaze announcing autumn, snow silence of winter. Japan lives by the seasons.',
    category: 'lifestyle',
    images: ['/gallery/seasons_sakura.png', '/gallery/seasons_aki.png'],
    color: '#e89aaa',
  },
  {
    id: 'onsen',
    name: 'Onsen Hot Springs',
    nameEn: 'Sacred Waters',
    kanji: '温泉',
    period: 'Ancient–Present',
    description: 'Steam rising into cold mountain air, snowflakes melting on skin, mineral water healing what aches. Japan\'s oldest luxury — bathing in volcanic gift.',
    category: 'lifestyle',
    images: ['/gallery/onsen.png', '/gallery/onsen_2.png'],
    color: '#6a9ab8',
  },
];